import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const inter = localFont({
	src: [
		{
			path: '../../public/fonts/InterTight-VariableFont_wght.ttf',
			weight: '500',
			style: 'normal',
		},
	],
	variable: '--font-inter',
});

const neueMetana = localFont({
	src: [
		{
			path: '../../public/fonts/NeueMetana-Regular.otf',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../../public/fonts/NeueMetana-Regular.otf',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../../public/fonts/NeueMetana-Bold.otf',
			weight: '700',
			style: 'normal',
		},
	],
	variable: '--font-neue-metana',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${neueMetana.variable}`}>
				{children}
			</body>
		</html>
	);
}
